### ISSUE TITLE
YAML includes don't work well with contentlayer

### ISSUE THREAD

**Issue by kouliavtsev** [appsignal/appsignal-docs#670]
Follows: https://github.com/appsignal/docs-nextjs/issues/186

Code like this:

```yml
file_paths_notice: &file_paths_notice
  - <Notice>**Note**: The specified path cannot contain Operating Specific file system abstractions, such as the homedir symbol `~` for *NIX systems. This will be seen as a malformed path.</Notice>

...

options:
  - config_key: active
    ruby:
      description: |
        -*file_paths_notice
```

Throws errors during contenlayer builds. 

![Screenshot 2022-08-08 at 15 14 46](https://user-images.githubusercontent.com/1392575/183428581-4ae93b7c-1471-48b5-81f2-7376eccdb1ac.png)

For now, copied the block to make the builds work in https://github.com/appsignal/docs-nextjs/issues/92
